export { default as Dialog } from './Dialog.vue'
export { DialogClose } from 'radix-vue'
export { default as DialogContent } from './DialogContent.vue'
export { default as DialogDescription } from './DialogDescription.vue'
export { default as DialogFooter } from './DialogFooter.vue'
export { default as DialogHeader } from './DialogHeader.vue'
export { default as DialogPortal } from './DialogPortal.vue'
export { default as DialogTitle } from './DialogTitle.vue'
export { DialogTrigger } from 'radix-vue'
export { default as DialogOverlay } from './DialogOverlay.vue'
